# version: "3.8"

# services:
#   backend:
#     build: ./backend
#     container_name: yolo-backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend/models:/app/models  # keep your YOLO weights persistent

#   frontend:
#     build: ./frontend
#     container_name: yolo-frontend
#     ports:
#       - "3000:80"  # nginx serves on port 80, we map to 3000 locally
#     depends_on:
#       - backend
